# Generated by Django 2.2.11 on 2020-03-29 05:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import flexible.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Conditions',
            },
        ),
        migrations.CreateModel(
            name='CSVFileImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CSV File Imports',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.SlugField(max_length=256)),
                ('verbose_name', models.CharField(max_length=256)),
                ('required', models.BooleanField()),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('evaluated', models.BooleanField(default=False)),
                ('generate_metrics', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fields',
            },
        ),
        migrations.CreateModel(
            name='FieldExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Field expressions',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ready', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexible.Model')),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='ModelExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Model')),
            ],
            options={
                'verbose_name_plural': 'Model expressions',
            },
        ),
        migrations.CreateModel(
            name='ModelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Model')),
            ],
            options={
                'verbose_name_plural': 'Model Instances',
            },
        ),
        migrations.CreateModel(
            name='AlwaysFalseCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
            ],
            options={
                'verbose_name_plural': 'Always false conditions',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='AlwaysTrueCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
            ],
            options={
                'verbose_name_plural': 'Always true conditions',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='BooleanField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Boolean Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Date Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='DecimalField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Decimal Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='DurationField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Duration Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='EmailField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Email Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='HasAttributeCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
                ('attribute_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Has attribute conditions',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Integer Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='LogMessageAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('message', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Log message Actions',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnAttributeAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('attribute_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Return attribute action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnBooleanAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Return boolean action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnDateAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Return date action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnDecimalAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Return decimal action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnDurationAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Return duration action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnEmailAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Return email action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnIntegerAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Return Integer Actions',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnStringAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Return string action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Field')),
                ('dropdown', models.BooleanField(default=False)),
                ('fixed_choices', models.BooleanField(default=True)),
                ('text_area', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Text Fields',
            },
            bases=('flexible.field',),
        ),
        migrations.CreateModel(
            name='ModelExpressionConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.TextField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], null=True)),
                ('index', models.IntegerField(default=0)),
                ('nested', models.BooleanField(default=False)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelExpression')),
            ],
            options={
                'verbose_name_plural': 'Model expression condition groups',
            },
        ),
        migrations.CreateModel(
            name='ModelExpressionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.TextField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], null=True)),
                ('index', models.IntegerField(default=0)),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Condition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelExpressionConditionGroup')),
            ],
            options={
                'verbose_name_plural': 'Model expression conditions',
            },
        ),
        migrations.CreateModel(
            name='ModelExpressionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Action')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelExpression')),
            ],
            options={
                'verbose_name_plural': 'Model expression actions',
            },
        ),
        migrations.CreateModel(
            name='ModelDescriptionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Model')),
            ],
            options={
                'verbose_name_plural': 'Model Description Components',
            },
        ),
        migrations.CreateModel(
            name='FieldExpressionConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.TextField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], null=True)),
                ('index', models.IntegerField(default=0)),
                ('nested', models.BooleanField(default=False)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.FieldExpression')),
            ],
            options={
                'verbose_name_plural': 'Field expression condition groups',
            },
        ),
        migrations.CreateModel(
            name='FieldExpressionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.TextField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], null=True)),
                ('index', models.IntegerField(default=0)),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Condition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.FieldExpressionConditionGroup')),
            ],
            options={
                'verbose_name_plural': 'Field expression conditions',
            },
        ),
        migrations.CreateModel(
            name='FieldExpressionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Action')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.FieldExpression')),
            ],
            options={
                'verbose_name_plural': 'Field expression actions',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='model',
            field=models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.Model'),
        ),
        migrations.AddField(
            model_name='field',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_flexible.field_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='DefaultFieldExpressionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Action')),
                ('expression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.FieldExpression')),
            ],
            options={
                'verbose_name_plural': 'Default field expression actions',
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='model',
            field=models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.Model'),
        ),
        migrations.AddField(
            model_name='condition',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_flexible.condition_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='AlternateModelExpressionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flexible.Action')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelExpression')),
            ],
            options={
                'verbose_name_plural': 'Alternate model expression actions',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='model',
            field=models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.Model'),
        ),
        migrations.AddField(
            model_name='action',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_flexible.action_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='TextFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'TextField Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='TextFieldCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
                ('rhs', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('exist', 'Exists'), ('match', 'Matches'), ('doesnotmatch', 'Does Not Match')], default='match', max_length=32)),
                ('field', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.TextField')),
            ],
            options={
                'verbose_name_plural': 'TextField conditions',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='ShowFieldAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('field', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Show Field Actions',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='ReturnDaysBetweenDatesAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('end', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, related_name='end', to='flexible.DateField')),
                ('start', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, related_name='start', to='flexible.DateField')),
            ],
            options={
                'verbose_name_plural': 'Return days between dates action',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='NestedModelExpressionConditionGroup',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
                ('child_group', models.OneToOneField(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.ModelExpressionConditionGroup')),
                ('parent_group', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, related_name='nestedgroups_set', to='flexible.ModelExpressionConditionGroup')),
            ],
            options={
                'verbose_name_plural': 'Nested model expression condition groups',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='NestedFieldExpressionConditionGroup',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
                ('child_group', models.OneToOneField(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.FieldExpressionConditionGroup')),
                ('parent_group', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, related_name='nestedgroups_set', to='flexible.FieldExpressionConditionGroup')),
            ],
            options={
                'verbose_name_plural': 'Nested field expression condition groups',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='IntegerFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Integer Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='HideFieldAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('field', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.Field')),
            ],
            options={
                'verbose_name_plural': 'Hide Field Actions',
            },
            bases=('flexible.action',),
        ),
        migrations.CreateModel(
            name='FormatDateFieldAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Action')),
                ('format', models.CharField(max_length=256)),
                ('field', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.DateField')),
            ],
            options={
                'verbose_name_plural': 'Format DateField Actions',
            },
            bases=('flexible.action',),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'model')},
        ),
        migrations.CreateModel(
            name='EmailFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.EmailField(max_length=254)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Email Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='DurationFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DurationField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Duration Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='DecimalFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Decimal Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='DateFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Date Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='BooleanFieldInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.Field')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.ModelInstance')),
            ],
            options={
                'verbose_name_plural': 'Boolean Field Instances',
                'unique_together': {('field', 'model_instance')},
            },
        ),
        migrations.CreateModel(
            name='BooleanFieldCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flexible.Condition')),
                ('rhs', models.BooleanField()),
                ('field', models.ForeignKey(on_delete=flexible.models.NON_POLYMORPHIC_CASCADE, to='flexible.BooleanField')),
            ],
            options={
                'verbose_name_plural': 'Boolean Field conditions',
            },
            bases=('flexible.condition',),
        ),
        migrations.CreateModel(
            name='TextFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.TextField')),
            ],
            options={
                'verbose_name_plural': 'Text Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='IntegerFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.IntegerField')),
            ],
            options={
                'verbose_name_plural': 'Integer Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='EmailFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.EmailField(max_length=254)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.EmailField')),
            ],
            options={
                'verbose_name_plural': 'Email Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DurationFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.DurationField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.DurationField')),
            ],
            options={
                'verbose_name_plural': 'Duration Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DecimalFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.DecimalField')),
            ],
            options={
                'verbose_name_plural': 'Decimal Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DateFieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=256)),
                ('value', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexible.DateField')),
            ],
            options={
                'verbose_name_plural': 'Date Field choices',
                'unique_together': {('field', 'value'), ('field', 'slug')},
            },
        ),
    ]
